#!\bin\sh
blue='\e[1;34m'
cyan='\e[0;36m'
green='\033[92m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
grey="\033[0;37m"
purple="\033[0;35m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
mon="mon"
lightcyan='\e[96m'
white='\e[1;37m'
nc="\e[0m"
red='\e[1;31m'
yellow='\e[1;33m'
#Loading
lod(){
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25   
}
################################
# Lah Bodo Amat Lah Bacod Amat #
################################
#Function start
start(){
lod
clear
echo -e $red"╔═╗┬┌─┬ ┬  ┬┌┐┌┌─┐┌┬┐┌─┐┬  ┬  ┌─┐┬─┐"
sleep 0.25
echo -e $white"╚═╗├┴┐└┬┘  ││││└─┐ │ ├─┤│  │  ├┤ ├┬┘"
sleep 0.25
echo -e $red"╚═╝┴ ┴ ┴   ┴┘└┘└─┘ ┴ ┴ ┴┴─┘┴─┘└─┘┴└─"
sleep 1 
}
start
echo 
echo -e $white"╭|$red════════════════════════$white|╮"
sleep 0.25
echo -e $white" |   $red HAPPY INSTALLING      $white|"
sleep 0.25
echo -e $white" |    1.$red RED_HAWK           $white|"
sleep 0.25
echo -e $white" |    2.$red Admin Finder       $white|"
sleep 0.25
echo -e $white" |    3.$red Dork Fresh         $white|"
sleep 0.25
echo -e $white" |    4.$red Spam Call/Sms      $white|"
sleep 0.25
echo -e $white" |    5.$red Webdav             $white|"
sleep 0.25
echo -e $white" |    6.$red Matrix             $white|"
sleep 0.25
echo -e $white" |    7.$red KK KTP FAKE        $white|"
sleep 0.25
echo -e $white" |    8.$red Crack Hash         $white|"
sleep 0.25
echo -e $white" |    9.$red Metasploit         $white|"
sleep 0.25
echo -e $white" |    10.$red Fb_react          $white|"
sleep 0.25
echo -e $white"╰|$red════════════════════════$white|╯"
sleep 0.25
echo -e $white"╭══[$red./root@localhost$white]══[$red./installer$white]═╮"
echo -n -e $white"╰══[$red.pilih$white]>"
read -e pilih

if [ $pilih = "1" ]
apt-get install php
clear 
pkg install php 
git clone https://github.com/Tuhinshubhra/RED_HAWK
cd RED_HAWK
php rhawk.php

if [ $pilih = "2" ]
apt-get install php
clear 
pkg install php 
git clone https://github.com/mrcakil/admin_finder
cd admin_finder
php adfin.php 

if [ $pilih = "3" ]
apt-get install wget
clear 
pkg install wget
clear 
read -p "Masukan Nama File : " file 
wget https://pastebin.com/raw/VnjR34YM -o $file
clear 
mv $file /sdcard/0/downloads
echo -e "Silahkan Cek Folder Downloads"

if [ $pilih = "4" ]
apt-get install php
clear
pkg install php
clear
pkg install wget
clear 
apt-get install wget
clear
wget https://raw.githubusercontent.com/tampansky/SPAM.php/master/call.php -o call.php
php call.php 

if [ $pilih = "5" ]
echo -e $cyan "[!]Membuka penyimpanan[!]"
termux-setup-storage
pkg upgrade 
clear
echo -e $cyan "[!]Menginstall Ruby[!]"
pkg install ruby 
sleep 1
clear
echo -e $cyan "[!]Menginstall lolcat[!]"
gem install lolcat 
clear
sleep 1
echo -e $cyan "[!]Menginstall CURL[!]"
pkg install curl 
wget https://raw.githubusercontent.com/tampansky/WD/master/setup -o webdav.sh 
clear
bash webdav.sh 

if [ $pilih = "6" ]
apt-get install cmatrix
pkg install cmatrix
cmatrix

if [ $pilih = "7" ]
apt-get install php 
pkg install php git
git clone https://github.com/IndonesianSecurity/kkktp
cd kkktp
php kkktp.php

if [ $pilih = "8" ]
apt-get install python2 
clear
pkg install python2
clear
git clone https://github.com/FajriHidayat088/FHX-Hash-Killer/
cd FHX-Hash-Killer
python2 FHXhashKiller.py

if [ $pilih = "9" ]
apt-get install wget
pkg install wget
wget https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh -o msf.sh 
bash msf.sh 

if [ $pilih = "10" ]
apt-get install php 
clear
pkg install php 
clear 
git clone https://github.com/AMVengeance/FB-React
cd Fb_react
bash start
